version: '3.5'
name: menu_service

services:
    web.facade:
        container_name: menu_webfacade
        image: menu_webfacade
        ports:
            - "5291:80"
        build: '../'
        environment:
            ConnectionStrings__DatabaseConnection: 'Data Source=mssql_server; Initial Catalog=MenuService; User ID=SA; Password=Adminadmin1@'
            CloudinarySettings__Cloud: 'dlg0te4gv'
            CloudinarySettings__ApiKey: '638166546729614'
            CloudinarySettings__ApiSecret: 'RlwGaUbXr64epMtYqRq3pUa4L_I'
        networks:
            - app_bridge_network

networks:
    app_bridge_network:
        name: app_bridge_network
        driver: bridge
        external: true